# Generated by Django 3.1.5 on 2021-01-10 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportifyApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bookings',
            field=models.ManyToManyField(related_name='courseBookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
